title: "Play with Chemistry"
baseurl: "/Play-with-chemistry" # the subpath of your site
url: "https://tirthaboss.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
